### ISSUE TITLE
Correct conflict between S10.1/10.2 on how many LLADDR options can be in IA_LL

### ISSUE THREAD

**Issue by bevolz** [dhcwg/dhcp-mac#2]
As Tomek noticed:
10.1:
Each IA_LL carries one block of link-layer addresses.
10.2:
More than one LLADDR option can appear in an IA_LL option.

Need to determine which it is. Probably best not to restrict?

**Comment by tomaszmrugalski** [comment]
As discussed on 2018-04-04, we'll go with allowing multiple ones.

**Comment by helinhl** [comment]
Support multiple ones.

**Comment by tomaszmrugalski** [comment]
Text updated.
