### ISSUE TITLE
Do we want to support reconfigure?

### ISSUE THREAD

**Issue by tomaszmrugalski** [dhcwg/dhcp-mac#5]
Make it forbidden/allowed/mandatory?

The argument for making it forbidden is simplified client and some of the IOT devices are really low capability.

The argument for making it mandatory is to make the address acquisition more dynamic. One of the arguments raised against IPv6 address assignment in DHCPv6 was that it was not really dynamic in the sense that once assigned the client couldn't be convinced to change an address, at least not immediately and had to wait till T1 elapses, which sometimes means days.

The compromise - to make it optional - seems to have disadvantages of the two approaches. Client implementors may implement it, but it may not work, since the server is not required to implement it. As such it will be rarely implemented. Operators can't really use it, because there is no guarantee that it will work (as most clients won't support it).

**Comment by bevolz** [comment]
Bernie's vote is allowed. Client may request, server may honor. But no requirement to implement. That's inline with 3315 (3315bis).

**Comment by bevolz** [comment]
Mention Reconfigure may be used (not normative) and refer to 3315bis document.

**Comment by helinhl** [comment]
Allowed. The protocol should support this feature, and whether the implementation of this feature depends on specific scenarios. For low-capacity LoT devices, implementors may not implement it. For reconfigure-required scenarios, implementors can implement it.

**Comment by tomaszmrugalski** [comment]
Added the following text:

>    Devices supporting this proposal MAY support reconfigure mechanism,
   as defined in Section 18.2.11 of [I-D.ietf-dhc-rfc3315bis].  If
   supported by both server and client, this mechanism allows the
   administrator to immediately notify clients that the configuration
   has changed and triggers retrieval of relevant changes immediately,
   rather than after T1 timer elapses.  Since this mechanism requires
   implementation of Reconfigure Key Authentication Protocol (See
   Section 20.4 of [I-D.ietf-dhc-rfc3315bis]), small footprint devices
   may chose to not support it.

Hopefully that clarifies the issue. Reconfigure is a cool feature, but there's a price attached. Smaller footprint devices may consider it's not worth the effort.
