### ISSUE TITLE
Can the server expand already assigned block?

### ISSUE THREAD

**Issue by tomaszmrugalski** [dhcwg/dhcp-mac#7]
The question is whether the server is allowed to expand a block of addresses that is already assigned. The argument in favor is to better cover hypervisor case that over time will need more and more addresses. If block expansion is not allowed, then the hypervisor client will send more complex messages over time (with multiple IA_LL containers).

The counter-argument here is that it may increase the complexity of the allocation mechanism.

Also, there's a related question: if we decide to allow expansion, why not contraction? This would give more flexibility at the price of increased complexity. For example, imagine a case of client getting a block of 100 addresses. It then sends a renewal with the address block shrunk to 80 addresses. What does it mean for the other 20 addresses? Are they still valid, but not extended? Are they implicitly released?

This may complicate the protocol significantly, so perhaps the best choice here is to simply not allow any block mutation during its lifetime?

**Comment by bevolz** [comment]
Document that the blocks are "fixed" once assigned (until release/expired).

**Comment by bevolz** [comment]
Added text that block must state the same in 8. Renewing Addresses. May need to be added elsewhere?
